apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
  namespace: openshift-nfd
spec:
  instance: "" # instance is empty by default
  operand:
    namespace: openshift-nfd
    image: quay.io/openshift/origin-node-feature-discovery:4.8
    imagePullPolicy: Always
  workerConfig:
    configData: |
      sources:
        custom:
        - name: "my.pci.feature"
          matchOn:
            - pciId :
                vendor: ["1c2c"]
                device: ["1000"]
            - usbId:
                vendor: ["1546"]
                device: ["01a9"]
            - pciId :
                vendor: ["1c2c"]
                device: ["1001"]
            - pciId :
                vendor: ["1c2c"]
                device: ["1002"]
            - pciId :
                vendor: ["8086"]
                device: ["1591"]
            - pciId :
                vendor: ["8086"]
                device: ["1591"]
                subsystem_vendor: ["1374"]
                subsystem_device: ["02d8"]
            - pciId :
                vendor: ["1c2c"]
                device: ["0000"]
