name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '30 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install xmllint
      run: sudo apt-get install -y libxml2-utils
    - uses: actions/checkout@v2
    - uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: quay.io/silicom
        username: ${{ secrets.QUAY_STS_USER }}
        password: ${{ secrets.QUAY_STS_TOKEN }}
    
    - name: Ice supported
      run: make charts-image

    - name: Push Ice supported
      run: make charts-image-push

    - name: Ice unsupported
      run: make charts-image-unsupported
  
    - name: Push Ice unsupported
      run: make charts-image-unsupported-push

