name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: quay.io/silicom
        username: silicom+github_sts_operator
        password: ${{ secrets.QUAY_STS_TOKEN }}
    
    - name: Ice supported
      run: make charts-image
      
    - name: Ice unsupported
      run: make charts-image-unsupported
  
    - name: Push Ice unsupported
      run: make charts-image-unsupported-push

    - name: Push Ice supported
      run: make charts-image-supported-push
